name: Update overlay.json

on:
  workflow_dispatch:
    inputs:
      user:
        required: true
      payload:
        required: true

jobs:
  update-overlay:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update overlay.json
        run: |
          echo '${{ github.event.inputs.payload }}' > overlay.json

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update overlay.json"
          file_pattern: overlay.json
        env:
          GITHUB_TOKEN: ${{ secrets.MKADP_TOKEN }}
