name: Update overlay.json

on:
  repository_dispatch:
    types: [overlay_update]

jobs:
  update-overlay:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update overlay.json
        run: |
          echo '${{ github.event.client_payload.payload }}' > overlay.json

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update overlay.json"
          file_pattern: overlay.json
        env:
          GITHUB_TOKEN: ${{ secrets.MKADP_TOKEN }}
